production:
 create_from_remote: no
 use.user.selected.activities: yes

development:
 create_from_remote: no
 use.user.selected.activities: yes
 filing.number.prefix: FN101,FN102
 auto_set_appointment: true

test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
